name: micubacel_sdk
description: SDK to work with mi.cubacel.net web page
version: 0.0.1
repository: https://github.com/todo-devs/micubacel_sdk

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  html: ^0.14.0+4